id: A12409549
title: 'The Melodic Sound of the Conch: A Prayer for the Long Life of the Vajra Master
  Dongna Choktrul Rinpoche'
type: translation
pechas:
- I38439738
- IF40E1CCE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:45:13.367507
  last_modified_at: 2023-01-04 11:45:13.367516
  collections:
  - Dongna Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I38439738/2BD7: C6B2
  IF40E1CCE/76DC: C6B2
